title: Renartius page
author: @renartius
email: rntsza@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 My first page on guthub

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  renartius # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
